### PR TITLE
gh-217: Improves support for MIDI message encoding

### PR DESCRIPTION
**Pull request by colinbdclark**
This pull request includes:
- Fixes to @the-t-in-rtf's MIDI encoding functions
- Improvements to encoding & decoding unit tests so that they all pass and are based on a shared set of test definitions
- Renaming of "chan" to "channel" in MIDI messages specs
- Additional TODO comments describing our next steps

This could use some review and then, if you've got time, further work before we can merge it into Flocking. Thanks, @the-t-in-rtf; this is shaping up awesomely!

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
@colinbdclark, I've reviewed the changes and happy to go ahead and merge this, once we confirm where the browser tests are meant to work.  I tend to have a lot of Testem launchers installed, I noticed that the tests have unique failures on PhantomJS and Safari (at least on High Sierra).  PhantomJS is fair enough, but I was a bit surprised that Safari didn't work.  Here's the unique error:

```
TypeError: Value is not a sequence
Source: 	
http://localhost:7357/7550/tests/unit/html/band-tests.html:12
```

That failure completely prevents further tests from running in Safari.  Anyway, if Safari is out of scope, it seems like adding `--skip Safari,PhantomJS` (and any other unsupported browsers) to the `browser-test` script definition would help in verifying that the tests are passing.

**Comment by colinbdclark** [comment]
Safari is definitely supported, and all the tests are passing for me here on macOS Sierra. I am usually pretty slow to upgrade to new versions because audio applications tend to break easily.

I've got Safari 11.0.1 and the Safari Technology Preview 11.1 on my machine and the tests pass. Can you pass along any further error information when you run the band tests in Safari on High Sierra?

Thanks!

**Comment by the-t-in-rtf** [comment]
High Sierra also has 11.0.1 (13604.3.5), turns out it's down to the fact that I have the webdriver plugin installed, [see here for a discussion on StackOverflow](https://stackoverflow.com/questions/46913856/value-is-not-a-sequence-safari-exception).

With that disabled, I get a different test failure, namely:

```
not ok 18 Safari 11.0 - Composition #1: ./html/midi-tests.html
    ---
        actual: >
            [object Object]
        expected: >
            [object Object]
        stack: >
            runLoggingCallbacks@http://localhost:7357/1746/node_modules/infusion/tests/lib/qunit/js/qunit.js:1609:23
            push@http://localhost:7357/1746/node_modules/infusion/tests/lib/qunit/js/qunit.js:958:22
            propEqual@http://localhost:7357/1746/node_modules/infusion/tests/lib/qunit/js/qunit.js:579:13
            assertDeepEq@http://localhost:7357/1746/node_modules/infusion/tests/test-core/jqUnit/js/jqUnit.js:180:32
            testEncoding@http://localhost:7357/1746/tests/unit/js/midi-tests.js:200:28
            each@http://localhost:7357/1746/node_modules/infusion/src/framework/core/js/Fluid.js:522:21
            http://localhost:7357/1746/tests/unit/js/midi-tests.js:352:19
            run@http://localhost:7357/1746/node_modules/infusion/tests/lib/qunit/js/qunit.js:207:22
            http://localhost:7357/1746/node_modules/infusion/tests/lib/qunit/js/qunit.js:365:13
            process@http://localhost:7357/1746/node_modules/infusion/tests/lib/qunit/js/qunit.js:1457:24
            http://localhost:7357/1746/node_modules/infusion/tests/lib/qunit/js/qunit.js:483:12
        message: >
            flock.ugen.midiFreq tests: Encoding of JSON as raw MIDI: We should be able to encode a noteOff message.
        Log: |
    ...
```

**Comment by the-t-in-rtf** [comment]
I just confirmed that this was test output from another branch, this is confirmed working and IMO ready to merge so that we can continue the discussion on the other pull.  Thanks for getting this over the line!

**Pull request merged**
